name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Check and build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Clean
      run: cargo clean # make sure the workspace is clean
    - name: Check
      run: cargo check --verbose
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test
